src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\Timezone;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(length: 5)]
    private ?string $heure_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column(length: 5)]
    private ?string $heure_fin = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Vehicule $vehicule = null;

    #[ORM\Column(length: 8)]
    private ?string $user = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?StatutReservation $statut = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $observation = null;

    #[ORM\ManyToOne]
    private ?TypeDemande $type_demande = null;

    #[ORM\Column(length: 8, nullable: true)]
    private ?string $demandeur = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $message_valideur = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $observation_valideur = null;

    public function __construct()
    {
        $this->createdAt = new \DateTime('now', new \DateTimeZone('America/Guadeloupe'));
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getHeureDebut(): ?string
    {
        return $this->heure_debut;
    }

    public function setHeureDebut(string $heure_debut): static
    {
        $this->heure_debut = $heure_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getHeureFin(): ?string
    {
        return $this->heure_fin;
    }

    public function setHeureFin(string $heure_fin): static
    {
        $this->heure_fin = $heure_fin;

        return $this;
    }

    public function getVehicule(): ?Vehicule
    {
        return $this->vehicule;
    }

    public function setVehicule(?Vehicule $vehicule): static
    {
        $this->vehicule = $vehicule;

        return $this;
    }

    public function getUser(): ?string
    {
        return $this->user;
    }

    public function setUser(string $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(): static
    {
        $this->createdAt = new \DateTime('now');

        return $this;
    }

    public function getStatut(): ?StatutReservation
    {
        return $this->statut;
    }

    public function setStatut(?StatutReservation $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    public function getObservation(): ?string
    {
        return $this->observation;
    }

    public function setObservation(?string $observation): static
    {
        $this->observation = $observation;

        return $this;
    }

    public function getTypeDemande(): ?TypeDemande
    {
        return $this->type_demande;
    }

    public function setTypeDemande(?TypeDemande $type_demande): static
    {
        $this->type_demande = $type_demande;

        return $this;
    }

    public function getDemandeur(): ?string
    {
        return $this->demandeur;
    }

    public function setDemandeur(?string $demandeur): static
    {
        $this->demandeur = $demandeur;

        return $this;
    }

    public function getMessageValideur(): ?string
    {
        return $this->message_valideur;
    }

    public function setMessageValideur(?string $message_valideur): static
    {
        $this->message_valideur = $message_valideur;

        return $this;
    }

    public function getObservationValideur(): ?string
    {
        return $this->observation_valideur;
    }

    public function setObservationValideur(?string $observation_valideur): static
    {
        $this->observation_valideur = $observation_valideur;

        return $this;
    }
}

src/Controller/AccueilController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\Persistence\ManagerRegistry;

use App\Entity\Reservation;
use App\Entity\HoraireOuverture;
use App\Entity\StatutReservation;
use App\Entity\Vehicule;
use App\Entity\Atelier;
use App\Entity\User;
use App\Entity\Role;

use App\Service\MailService;
use App\Service\SsoService;
use App\Service\LdapService;

use App\Form\ReservationType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;

class AccueilController extends AbstractController
{
    private $app_const;
    private $em;
    private $requestStack, $session;
    public $request, $params;

    public function __construct(RequestStack $requestStack, ManagerRegistry $doctrine)
    {
        $this->em = $doctrine->getManager();

        $this->request = Request::createFromGlobals();
        $this->requestStack = $requestStack;
        $this->session = $this->requestStack->getSession();
        // /* paramètres session */
        $this->params = [
            'nigend' => $this->session->get('HTTP_NIGEND'),
            'unite' => $this->session->get('HTTP_UNITE'),
            'profil' => $this->session->get('HTTP_PROFIL'),
            'departement' => $this->session->get('HTTP_DEPARTEMENT'),
        ];
    }

    // #[Route('/access_denied', name: 'resa_access_denied')]
    // public function accessDenied(): Response
    // {
    //     $this->setAppConst();
    // }

    #[Route('/', name: 'resa_accueil')]
    public function accueil(): Response
    {

        $em_uniquement = false;

        if (is_null($this->params['nigend']))
            return $this->redirectToRoute('resa_login');

        $this->setAppConst();

        $curr_user = $this->em
            ->getRepository(User::class)
            ->findOneBy(['nigend' => $this->params['nigend']]);

        if ($curr_user->isEmUniquement())
            $em_uniquement = true;

        $env_vars = $this->getAppConst();
        $liste_unites_em = $env_vars['APP_UNITES_EM'] ?? [];
        $unites_em = explode(',', $liste_unites_em);
        $curr_unite = "" . (+$curr_user->getUnite()); // code unité en string sans zéro devant

        $vehicules = $this->em
            ->getRepository(Vehicule::class)
            ->findBy(['departement' => $this->params['departement']]);

        $vehicules = array_filter($vehicules, function ($vl) use ($unites_em, $curr_unite, $em_uniquement) {
            // On enlève les VLs en maintenance
            if ($vl->getRestriction()->getCode() === 'ATELIER')
                return false;
            // Si VL Etat-Major, on vérifie que l'utilisateur appartient à une unité EM
            if ($vl->getRestriction()->getCode() === 'EM')
                return $em_uniquement || in_array($curr_unite, $unites_em);

            if ($em_uniquement)
                return false;
            return true;
        });

        $categories = [];
        $transmissions = [];
        $category_ids = [];
        $transmission_ids = [];
        $unites = [];
        $unites_ids = [];
        foreach ($vehicules as $vl) {
            $cat = $vl->getCategorie();
            $cat_id = $cat->getId();
            $trans = $vl->getTransmission();
            $trans_id = $trans->getId();
            $unt = $vl->getUnite();
            $unt_id = $unt->getId();

            if (!in_array($unt_id, $unites_ids)) {
                $unites_ids[] = $unt_id;
                $unites[] = $unt;
            }

            if (!in_array($cat_id, $category_ids)) {
                $category_ids[] = $cat_id;
                $categories[] = $cat;
            }
            if (!in_array($trans_id, $transmission_ids)) {
                $transmission_ids[] = $trans_id;
                $transmissions[] = [
                    'code' => $trans->getCode(),
                    'libelle' => $trans->getLibelle()
                ];
            }
        }

        $atelier = $this->em
            ->getRepository(Atelier::class)
            ->findOneBy(
                $this->params['profil'] === 'CSAG' ?
                    ['code_unite' => $this->params['unite']] :
                    ['departement' => $this->params['departement']]
            );

        if (is_null($atelier))
            $atelier = $this->em
                ->getRepository(Atelier::class)
                ->findOneBy(
                    ['departement' => $this->params['departement']]
                );

        $horaires = $this->getBaseHoraires();

        $base_horaires = $this->em
            ->getRepository(HoraireOuverture::class)
            ->findBy(['code_unite' => $atelier]);
        if (count($base_horaires) == 0) {
            $jours_ouvrables = ['LU', 'MA', 'ME', 'JE', 'VE'];
            foreach ($jours_ouvrables as $jour) {
                for ($i = 0; $i <= 1; $i++) {
                    $horaire = new HoraireOuverture();
                    $horaire->setCodeUnite($atelier);
                    $horaire->setJour($jour);
                    if ($i === 0) {
                        $horaire->setCreneau('AM');
                        $horaire->setDebut('08:00');
                        $horaire->setFin('12:00');
                    } else {
                        $horaire->setCreneau('PM');
                        $horaire->setDebut('14:00');
                        $horaire->setFin('17:00');
                    }

                    $this->em->persist($horaire);
                    $this->em->flush();
                }
            };
        }

        $dates = [];
        $dates_fin = [];
        // $timezone = new \DateTimeZone('America/Guadeloupe');
        $now = new \DateTime('now');
        $max = new \DateTime('now');
        $max->modify('+' . $this->app_const['APP_LIMIT_RESA_MONTHS'] . ' months');
        $max_date = $max->format("Y-m-d");
        //$max->modify($this->app_const['APP_MAX_RESA_DURATION']);
        //$max->modify('- 1 days');
        $ok = false;
        for ($i = 0; $now->format("Y-m-d") !== $max->format("Y-m-d"); $i++) {
            $fr_date =  $this->FR($now->format('Y-m-d'));
            $atelier_ouvert = $this->getHorairesByDay(substr($fr_date, 0, 2), $horaires);
            if ($now->format("Y-m-d") === $max_date) {
                $ok = true;
            }

            if (!$ok) {
                $dates[] = [
                    'en' => $now->format('Y-m-d'),
                    'fr' => $i === 0 ? 'Aujourd\'hui' : ($i === 1 ? 'Demain' : $fr_date),
                    'short' => $i === 0 ? 'Auj.' : ($i === 1 ? 'Demain' : /*preg_replace('#\s.*#', ' ', $fr_date).*/ $now->format('d/m')),
                    'horaires' => $atelier_ouvert
                ];
            }

            $dates_fin[] = [
                'en' => $now->format('Y-m-d'),
                'fr' => $i === 0 ? 'Aujourd\'hui' : ($i === 1 ? 'Demain' : $fr_date),
                'short' => $i === 0 ? 'Auj.' : ($i === 1 ? 'Demain' : /*preg_replace('#\s.*#', ' ', $fr_date).*/ $now->format('d/m')),
                'horaires' => $atelier_ouvert
            ];
            $now->modify('+ 1 days');
        }

        $last_date = [];
        for ($i = count($dates) - 1; $i > 0; $i--) {
            if (count($dates_fin[$i]['horaires']) > 0) {
                $last_date = $dates_fin[$i];
                $i = 0;
            }
        }

        $badge_classes = [
            "NONE" => "",
            "EM" => "info",
            "AVT_JGT" => "warning",
            "ATELIER" => "",
            "DOTATION" => "green-menthe",
            "APR_JGT" => "blue-ecume"
        ];

        return $this->render('accueil/accueil.html.twig', array_merge(
            $this->getAppConst(),
            $this->params,
            [
                'vehicules' => $vehicules,
                'categories' => $categories,
                'transmissions' => $transmissions,
                'dates' => $dates,
                'dates_fin' => $dates_fin,
                'last_date' => $last_date,
                'unites' => $unites,
                'badge_classes' => $badge_classes
            ]
        ));
    }

    #[Route(path: '/reserver/{vl_id}', name: 'resa_reserver')]
    #[Route(path: '/reserver/{vl_id}/{from}/{to}', name: 'resa_reserver')]
    public function reserver(string $vl_id, string $from = '', string $to = ''): Response
    {
        if (is_null($this->params['nigend']))
            return $this->redirectToRoute('resa_login');

        $this->setAppConst();

        $filtered = true;
        $tmp = new \DateTime('now');
        $max = new \DateTime($tmp->format('Y-m-d') . ' 23:59:59');
        $max->modify('+' . $this->app_const['APP_LIMIT_RESA_MONTHS'] . ' months');

        if ($from === '') {
            $filtered = false;
            // $timezone = new \DateTimeZone('America/Guadeloupe');
            $now = new \DateTime('now');
            $now->modify('+ 1 days');
            $now->modify('+ 1 hours');
            $from =  $now;
            $to = $max;
        } else {
            $from = new \DateTime($from);
            $to = new \DateTime($to);
        }

        $vehicule = $this->em
            ->getRepository(Vehicule::class)
            ->findOneBy(['id' => $vl_id]);

        $statut_resa_en_attente = $this->em
            ->getRepository(StatutReservation::class)
            ->findOneBy(['code' => 'En attente']);

        $limit_resa = $this->app_const['APP_LIMIT_RESA_MONTHS'];
        $limit_resa = $limit_resa . ' mois';

        $horaires = $this->em
            ->getRepository(HoraireOuverture::class)
            ->findAll();

        $resa = new Reservation();
        $resa->setUser($this->params['nigend']);
        $resa->setVehicule($vehicule);
        $resa->setStatut($statut_resa_en_attente);

        if ($filtered) {
            $resa->setDateDebut($from);

templates/accueil/reserver/calendriers.html.twig
{# CALENDRIERS #}
<div
	id="calendars-container">
	{# source: https://gist.github.com/aknosis/3932192 #}
	{% set time = "now"| date('Y-m-15') | date_modify('-1 months')| date("U") %}
	{% for i in range(0,APP_LIMIT_RESA_MONTHS) %}
		{% set time =  time | date_modify('+1 months') %}
		<table>
			<thead>
				{% if loop.first %}
					<tr class="cs-row-days">
						<th width="15%" id="th-LU" data-horaires="{{ horaires.LU }}">
							Lu<span class="hide-s">ndi</span>
						</th>
						<th width="15%" id="th-MA" data-horaires="{{ horaires.MA }}">
							Ma<span class="hide-s">rdi</span>
						</th>
						<th width="16%" id="th-ME" data-horaires="{{ horaires.ME }}">
							Me<span class="hide-s">rcredi</span>
						</th>
						<th width="15%" id="th-JE" data-horaires="{{ horaires.JE }}">
							Je<span class="hide-s">udi</span>
						</th>
						<th width="15%" id="th-VE" data-horaires="{{ horaires.VE }}">
							Ve<span class="hide-s">ndredi</span>
						</th>
						<th width="12%" id="th-SA" data-horaires="{{ horaires.SA }}">
							Sa<span class="hide-s">medi</span>
						</th>
						<th width="12%" id="th-DI" data-horaires="{{ horaires.DI }}">
							Di<span class="hide-s">manche</span>
						</th>
					</tr>
				{% endif %}
				<tr>
					{% set trans_day_hash = { 
                    "January": "Janvier", 
                    "February": "Février", 
                    "March": "Mars", 
                    "April": "Avril", 
                    "May": "Mai", 
                    "June": "Juin", 
                    "July": "Juillet" ,
                    "August":"Août",
                    "September":"Septembre",
                    "October":"Octobre",
                    "November":"Novembre",
                    "December":"Décembre"
                } %}
					{% set days_list = [
                  'LU','MA','ME','JE','VE','SA','DI'
                ] %}
					<th colspan="7">
						{{ trans_day_hash[time|date('F')] }}
					</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					{% set daysInMonth = time|date('t') %}
					{% set startDow = time|date('F 1\\s\\t Y')|date('N') - 1 %}
					{% set dow = startDow %}
					{% for day in range(1,daysInMonth) %}
						{% if loop.first and startDow != 0 %}
							<td colspan="{{ startDow }}"></td>
						{% endif %}
						{% set curr_date = time|date('Y-m-' ~ (day|length > 1 ? day: '0'~day) ~ ' 23:59:00')|date('U') %}
						{% set before_now = curr_date <= ('now'|date('Y-m-d 00:00:00')|date('U') )? true : false %}
						{% set after_limit = curr_date > (max|date('Y-m-d 00:00:00')|date('U') )? true : false %}
						{% set csag_ferme =  horaires[days_list[dow]] == '' %}
						<td class="target">
							<div class="relative">

								{% set striked = false %}
								{% set striked_debut = false %}
								{% set striked_fin = false %}
								{% set mems = [] %}

								{% for i, reservation in vehicule.reservations %}
									{% if 
                              curr_date|date('Y-m-d')|date('U') >= date(reservation.dateDebut)|date('Y-m-d')|date('U') 
                                and 
                              curr_date|date('Y-m-d')|date('U') <= date(reservation.dateFin)|date('Y-m-d')|date('U') 
                              %}

										{% set striked_debut = (curr_date | date('Y-m-d')) == (date(reservation.dateDebut)|date('Y-m-d')) ? reservation.heureDebut : false %}
										{% set striked_fin = (curr_date | date('Y-m-d')) == (date(reservation.dateFin)|date('Y-m-d')) ? reservation.heureFin : false %}
										{# {% set striked = striked_debut or striked_fin ? false : true %} #}
										{% set striked = true %}

										{% set mem = [] %}
										{% set mem = mem|merge([{'debut': striked_debut, 'fin': striked_fin}]) %}
										{% set mems = mems|merge(mem) %}

									{% endif %}
								{% endfor %}

								<div {% for i, mem in mems %} {{ 'data-resa_'~ i ~ '_debut="'~ mem.debut ~'" data-resa_'~ i ~ '_fin="' ~ mem.fin ~ '"'}} {% endfor %} {{striked_debut ? 'data-heure_debut="' ~ striked_debut ~ '"' }} {{striked_fin ? 'data-heure_fin="' ~ striked_fin ~ '"' }} data-ref="{{ days_list[dow] }}" {{ (striked and striked_debut == false and striked_fin == false) or before_now or after_limit or csag_ferme ? '' : ' aria-controls="fr-modal--from" data-fr-opened="false"' }} class="cs-td-daynum{{ striked ? ' striked' }}{{ before_now ? ' before_now' }}{{ after_limit ? ' after_limit' }}{{ csag_ferme ? ' csag_ferme' }}{{ striked_debut ? ' striked_debut' }}{{ striked_fin ? ' striked_fin' }}" data-date="{{ time|date('Y-m-' ~ (day|length > 1 ? day : '0' ~ day)) }}" title="{{ striked ? 'Il y a une ou plusieurs réservations à cette date.' : striked_debut or striked_fin ? 'Le véhicule est réservé une partie de la journée' : before_now ? ' Date passée': after_limit ? ' Vous ne pouvez réserver au delà de ' ~ limit_resa: csag_ferme ? " En dehors des horaires d'ouverture du CSAG" : ' ' }}">
									{{ day }}
								</div>
								<div>
									{# day content here #}
								</div>
							</div>
						</td>
						{% if loop.last and dow != 6 %}
							<td colspan="{{ 6 - dow }}">
								&nbsp;
							</td>
						{% endif %}
						{% if dow == 6 %}
							{% set dow = 0 %}
						</tr>
						<tr>
						{% else %}
							{% set dow = dow + 1 %}
					{% endif %}
				{% endfor %}
			</tr>
		</tbody>
	</table>
{% endfor %}</div>{# FIN CALENDRIERS #}

templates/accueil/reserver/fil_arianne.html.twig
{# Fil d'Arianne #}
<nav role="navigation" class="hide-s hide-m fr-breadcrumb" aria-label="vous êtes ici :">
	<button class="fr-breadcrumb__button" aria-expanded="false" aria-controls="breadcrumb-1">
		Voir le fil d’Ariane
	</button>
	<div class="fr-collapse">
		<ol class="fr-breadcrumb__list">
			<li>
				<a href="{{ path('resa_accueil') }}" class="fr-breadcrumb__link">
					Accueil
				</a>
			</li>
			<li>
				<a class="fr-breadcrumb__link" aria-current="page">
					Réserver un véhicule
				</a>
			</li>
		</ol>
	</div>
</nav>

templates/accueil/reserver/modale_avant_jugement.html.twig
{# MODALE avant jugement #}
<dialog id="modal-restriction" class="fr-modal" aria-labelledby="modal-restriction-title" data-fr-concealing-backdrop="true">

	<div class="fr-container fr-container--fluid fr-container-md">
		<div class="fr-grid-row fr-grid-row--center">
			<div class="fr-col-12 fr-col-md-8 fr-col-lg-6">
				<div class="fr-modal__body">

					<div class="fr-modal__header"></div>

					<div class="fr-modal__content">
						<h2 id="modal-restriction-title" class="fr-modal__title align-left">
							<span class="fr-icon-info-line fr-icon--lg" aria-hidden="true"></span>
							{{ vehicule.restriction.libelle }}
						</h2>
						<p class="align-left">{{ vehicule.restriction.description }}</p>
					</div>
					<!-- fr-modal__content -->

					<div class="fr-modal__footer">
						<ul class="fr-btns-group fr-btns-group--right fr-btns-group--inline-reverse fr-btns-group--inline-lg fr-btns-group--icon-left">
							<li>
								<button id="form-submit-btn" type="submit" class="fr-btn fr-btn--md fr-fi-arrow-right-line fr-btn--icon-left">
									J'ai compris et je réserve
								</button>
							</li>
							<li>
								<button type="reset" aria-controls="modal-restriction" class="fr-btn--close fr-btn fr-icon-checkbox-circle-line fr-btn--icon-left fr-btn--secondary">Fermer</button>
							</li>
						</ul>
					</div>
					<!-- fr-modal__footer -->

				</div>
				<!-- fr-modal__body -->

			</div>
			<!-- fr-col-lg-6 -->

		</div>
		<!-- fr-grid-row -->

	</div>
	<!-- fr-container -->

</dialog>
{# FIN MODALE avant jugement #}

templates/accueil/reserver/modale_debut.html.twig
{# MODALE Début #}
<dialog aria-labelledby="fr-modal--from-title" id="fr-modal--from" class="fr-modal" role="dialog">
	<div class="fr-container fr-container--fluid fr-container-md">
		<div class="fr-grid-row fr-grid-row--center">
			<div class="fr-col-12 fr-col-md-8 fr-col-lg-6">

				<div class="fr-modal__body">
					<div
						id="step-1" class="fr-mt-1w fr-modal__content fr-grid-row">
						{# stepper #}
						<div id="fr-modal--from-title" class="fr-stepper fr-col-12">
							<h2 class="fr-stepper__title">
								Début de la réservation
								<span class="fr-stepper__state">
									Étape 1 sur 2
								</span>
							</h2>
							<div class="fr-stepper__steps" data-fr-current-step="1" data-fr-steps="2"></div>
						</div>

						<h3 class="fr-col-12 cs-date-lib" id="from-date-lib"></h3>

						<div id="notice-resa-from" class="hidden fr-col-12 fr-notice fr-notice--info">
							<div class="fr-container">
								<div class="fr-notice__body">
									<p>
										<span class="fr-notice__title">Information:</span>
										<div class="fr-notice__desc">
											Le véhicule est déjà réservé:&nbsp;<ul id="text-resa-from"></ul>
										</div>
									</p>
									<button title="Masquer le message" onclick="const notice = this.parentNode.parentNode.parentNode; notice.parentNode.removeChild(notice)" id="button-1299" class="fr-btn--close fr-btn">Masquer le message</button>
								</div>
							</div>
						</div>

						<div class="fr-grid-row fr-mb-2w">
							<div class=" fr-select-group fr-col fr-col-6 fr-pl-1w">
								<label class="fr-label" for="select-from-heure">
									Heure
								</label>
								<select class="fr-select" id="select-from-heure" name="select-from-heure"></select>

							</div>
							<div class="fr-select-group fr-select-group--disabled fr-col fr-col-6 fr-pl-1w cs-select-minutes">
								<label class="fr-label" for="select-from-minute">
									&nbsp;
								</label>
								<select class="fr-select" id="select-from-minute" name="select-from-minute">
									{% for i in range(0, 60, APP_MINUTES_SELECT_INTERVAL) %}
										{% if i < 60 %}
											<option value="{{ i | length > 1 ? i : '0' ~ i }}" {{ i == 0 ? 'selected' }}>
												{{ i | length > 1 ? i : '0' ~ i }}
											</option>
										{% endif %}
									{% endfor %}
								</select>
							</div>
						</div>

						<div class="cs-btns-group fr-btns-group">
							<button id="modal-suivant" type="button" aria-controls="fr-modal--from" class="fr-btn fr-btn--tertiary-no-outline">
								Date de fin &#8594;
							</button>
						</div>

					</div>
					{# fin étape DÉBUT #}
				</div>

			</div>
		</div>
	</div>
</dialog>
{# FIN MODALE Début #}