src/Entity/Unite.php
<?php

namespace App\Entity;

use App\Repository\UniteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UniteRepository::class)]
class Unite
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $code_unite = null;

    #[ORM\Column(length: 25)]
    private ?string $nom_court = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom_long = null;

    /**
     * @var Collection<int, HoraireOuverture>
     */
    #[ORM\OneToMany(targetEntity: HoraireOuverture::class, mappedBy: 'code_unite', orphanRemoval: true)]
    private Collection $horaires_ouverture;

    #[ORM\Column(nullable: true)]
    private ?int $departement = null;

    /**
     * @var Collection<int, Vehicule>
     */
    #[ORM\OneToMany(targetEntity: Vehicule::class, mappedBy: 'unite')]
    private Collection $vehicules;

    public function __construct()
    {
        $this->horaires_ouverture = new ArrayCollection();
        $this->vehicules = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeUnite(): ?int
    {
        return $this->code_unite;
    }

    public function setCodeUnite(int $code_unite): static
    {
        $this->code_unite = $code_unite;

        return $this;
    }

    public function getNomCourt(): ?string
    {
        return $this->nom_court;
    }

    public function setNomCourt(string $nom_court): static
    {
        $this->nom_court = $nom_court;

        return $this;
    }

    public function getNomLong(): ?string
    {
        return $this->nom_long;
    }

    public function setNomLong(?string $nom_long): static
    {
        $this->nom_long = $nom_long;

        return $this;
    }

    /**
     * @return Collection<int, HoraireOuverture>
     */
    public function getHorairesOuverture(): Collection
    {
        return $this->horaires_ouverture;
    }

    public function addHorairesOuverture(HoraireOuverture $horairesOuverture): static
    {
        if (!$this->horaires_ouverture->contains($horairesOuverture)) {
            $this->horaires_ouverture->add($horairesOuverture);
            $horairesOuverture->setCodeUnite($this);
        }

        return $this;
    }

    public function removeHorairesOuverture(HoraireOuverture $horairesOuverture): static
    {
        if ($this->horaires_ouverture->removeElement($horairesOuverture)) {
            // set the owning side to null (unless already changed)
            if ($horairesOuverture->getCodeUnite() === $this) {
                $horairesOuverture->setCodeUnite(null);
            }
        }

        return $this;
    }

    public function getDepartement(): ?int
    {
        return $this->departement;
    }

    public function setDepartement(?int $departement): static
    {
        $this->departement = $departement;

        return $this;
    }

    /**
     * @return Collection<int, Vehicule>
     */
    public function getVehicules(): Collection
    {
        return $this->vehicules;
    }

    public function addVehicule(Vehicule $vehicule): static
    {
        if (!$this->vehicules->contains($vehicule)) {
            $this->vehicules->add($vehicule);
            $vehicule->setUnite($this);
        }

        return $this;
    }

    public function removeVehicule(Vehicule $vehicule): static
    {
        if ($this->vehicules->removeElement($vehicule)) {
            // set the owning side to null (unless already changed)
            if ($vehicule->getUnite() === $this) {
                $vehicule->setUnite(null);
            }
        }

        return $this;
    }
}

src/Controller/AccueilController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\Persistence\ManagerRegistry;

use App\Entity\Reservation;
use App\Entity\HoraireOuverture;
use App\Entity\StatutReservation;
use App\Entity\Vehicule;
use App\Entity\Atelier;
use App\Entity\User;
use App\Entity\Role;

use App\Service\MailService;
use App\Service\SsoService;
use App\Service\LdapService;

use App\Form\ReservationType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;

class AccueilController extends AbstractController
{
    private $app_const;
    private $em;
    private $requestStack, $session;
    public $request, $params;

    public function __construct(RequestStack $requestStack, ManagerRegistry $doctrine)
    {
        $this->em = $doctrine->getManager();

        $this->request = Request::createFromGlobals();
        $this->requestStack = $requestStack;
        $this->session = $this->requestStack->getSession();
        // /* paramètres session */
        $this->params = [
            'nigend' => $this->session->get('HTTP_NIGEND'),
            'unite' => $this->session->get('HTTP_UNITE'),
            'profil' => $this->session->get('HTTP_PROFIL'),
            'departement' => $this->session->get('HTTP_DEPARTEMENT'),
        ];
    }

    // #[Route('/access_denied', name: 'resa_access_denied')]
    // public function accessDenied(): Response
    // {
    //     $this->setAppConst();
    // }

    #[Route('/', name: 'resa_accueil')]
    public function accueil(): Response
    {

        $em_uniquement = false;

        if (is_null($this->params['nigend']))
            return $this->redirectToRoute('resa_login');

        $this->setAppConst();

        $curr_user = $this->em
            ->getRepository(User::class)
            ->findOneBy(['nigend' => $this->params['nigend']]);

        if ($curr_user->isEmUniquement())
            $em_uniquement = true;

        $env_vars = $this->getAppConst();
        $liste_unites_em = $env_vars['APP_UNITES_EM'] ?? [];
        $unites_em = explode(',', $liste_unites_em);
        $curr_unite = "" . (+$curr_user->getUnite()); // code unité en string sans zéro devant

        $vehicules = $this->em
            ->getRepository(Vehicule::class)
            ->findBy(['departement' => $this->params['departement']]);

        $vehicules = array_filter($vehicules, function ($vl) use ($unites_em, $curr_unite, $em_uniquement) {
            // On enlève les VLs en maintenance
            if ($vl->getRestriction()->getCode() === 'ATELIER')
                return false;
            // Si VL Etat-Major, on vérifie que l'utilisateur appartient à une unité EM
            if ($vl->getRestriction()->getCode() === 'EM')
                return $em_uniquement || in_array($curr_unite, $unites_em);

            if ($em_uniquement)
                return false;
            return true;
        });

        $categories = [];
        $transmissions = [];
        $category_ids = [];
        $transmission_ids = [];
        $unites = [];
        $unites_ids = [];
        foreach ($vehicules as $vl) {
            $cat = $vl->getCategorie();
            $cat_id = $cat->getId();
            $trans = $vl->getTransmission();
            $trans_id = $trans->getId();
            $unt = $vl->getUnite();
            $unt_id = $unt->getId();

            if (!in_array($unt_id, $unites_ids)) {
                $unites_ids[] = $unt_id;
                $unites[] = $unt;
            }

            if (!in_array($cat_id, $category_ids)) {
                $category_ids[] = $cat_id;
                $categories[] = $cat;
            }
            if (!in_array($trans_id, $transmission_ids)) {
                $transmission_ids[] = $trans_id;
                $transmissions[] = [
                    'code' => $trans->getCode(),
                    'libelle' => $trans->getLibelle()
                ];
            }
        }

        $atelier = $this->em
            ->getRepository(Atelier::class)
            ->findOneBy(
                $this->params['profil'] === 'CSAG' ?
                    ['code_unite' => $this->params['unite']] :
                    ['departement' => $this->params['departement']]
            );

        if (is_null($atelier))
            $atelier = $this->em
                ->getRepository(Atelier::class)
                ->findOneBy(
                    ['departement' => $this->params['departement']]
                );

        $horaires = $this->getBaseHoraires();

        $base_horaires = $this->em
            ->getRepository(HoraireOuverture::class)
            ->findBy(['code_unite' => $atelier]);
        if (count($base_horaires) == 0) {
            $jours_ouvrables = ['LU', 'MA', 'ME', 'JE', 'VE'];
            foreach ($jours_ouvrables as $jour) {
                for ($i = 0; $i <= 1; $i++) {
                    $horaire = new HoraireOuverture();
                    $horaire->setCodeUnite($atelier);
                    $horaire->setJour($jour);
                    if ($i === 0) {
                        $horaire->setCreneau('AM');
                        $horaire->setDebut('08:00');
                        $horaire->setFin('12:00');
                    } else {
                        $horaire->setCreneau('PM');
                        $horaire->setDebut('14:00');
                        $horaire->setFin('17:00');
                    }

                    $this->em->persist($horaire);
                    $this->em->flush();
                }
            };
        }

        $dates = [];
        $dates_fin = [];
        // $timezone = new \DateTimeZone('America/Guadeloupe');
        $now = new \DateTime('now');
        $max = new \DateTime('now');
        $max->modify('+' . $this->app_const['APP_LIMIT_RESA_MONTHS'] . ' months');
        $max_date = $max->format("Y-m-d");
        //$max->modify($this->app_const['APP_MAX_RESA_DURATION']);
        //$max->modify('- 1 days');
        $ok = false;
        for ($i = 0; $now->format("Y-m-d") !== $max->format("Y-m-d"); $i++) {
            $fr_date =  $this->FR($now->format('Y-m-d'));
            $atelier_ouvert = $this->getHorairesByDay(substr($fr_date, 0, 2), $horaires);
            if ($now->format("Y-m-d") === $max_date) {
                $ok = true;
            }

            if (!$ok) {
                $dates[] = [
                    'en' => $now->format('Y-m-d'),
                    'fr' => $i === 0 ? 'Aujourd\'hui' : ($i === 1 ? 'Demain' : $fr_date),
                    'short' => $i === 0 ? 'Auj.' : ($i === 1 ? 'Demain' : /*preg_replace('#\s.*#', ' ', $fr_date).*/ $now->format('d/m')),
                    'horaires' => $atelier_ouvert
                ];
            }

            $dates_fin[] = [
                'en' => $now->format('Y-m-d'),
                'fr' => $i === 0 ? 'Aujourd\'hui' : ($i === 1 ? 'Demain' : $fr_date),
                'short' => $i === 0 ? 'Auj.' : ($i === 1 ? 'Demain' : /*preg_replace('#\s.*#', ' ', $fr_date).*/ $now->format('d/m')),
                'horaires' => $atelier_ouvert
            ];
            $now->modify('+ 1 days');
        }

        $last_date = [];
        for ($i = count($dates) - 1; $i > 0; $i--) {
            if (count($dates_fin[$i]['horaires']) > 0) {
                $last_date = $dates_fin[$i];
                $i = 0;
            }
        }

        $badge_classes = [
            "NONE" => "",
            "EM" => "info",
            "AVT_JGT" => "warning",
            "ATELIER" => "",
            "DOTATION" => "green-menthe",
            "APR_JGT" => "blue-ecume"
        ];

        return $this->render('accueil/accueil.html.twig', array_merge(
            $this->getAppConst(),
            $this->params,
            [
                'vehicules' => $vehicules,
                'categories' => $categories,
                'transmissions' => $transmissions,
                'dates' => $dates,
                'dates_fin' => $dates_fin,
                'last_date' => $last_date,
                'unites' => $unites,
                'badge_classes' => $badge_classes
            ]
        ));
    }

    #[Route(path: '/reserver/{vl_id}', name: 'resa_reserver')]
    #[Route(path: '/reserver/{vl_id}/{from}/{to}', name: 'resa_reserver')]
    public function reserver(string $vl_id, string $from = '', string $to = ''): Response
    {
        if (is_null($this->params['nigend']))
            return $this->redirectToRoute('resa_login');

        $this->setAppConst();

        $filtered = true;
        $tmp = new \DateTime('now');
        $max = new \DateTime($tmp->format('Y-m-d') . ' 23:59:59');
        $max->modify('+' . $this->app_const['APP_LIMIT_RESA_MONTHS'] . ' months');

        if ($from === '') {
            $filtered = false;
            // $timezone = new \DateTimeZone('America/Guadeloupe');
            $now = new \DateTime('now');
            $now->modify('+ 1 days');
            $now->modify('+ 1 hours');
            $from =  $now;
            $to = $max;
        } else {
            $from = new \DateTime($from);
            $to = new \DateTime($to);
        }

        $vehicule = $this->em
            ->getRepository(Vehicule::class)
            ->findOneBy(['id' => $vl_id]);

        $statut_resa_en_attente = $this->em
            ->getRepository(StatutReservation::class)
            ->findOneBy(['code' => 'En attente']);

        $limit_resa = $this->app_const['APP_LIMIT_RESA_MONTHS'];
        $limit_resa = $limit_resa . ' mois';

        $horaires = $this->em
            ->getRepository(HoraireOuverture::class)
            ->findAll();

        $resa = new Reservation();
        $resa->setUser($this->params['nigend']);
        $resa->setVehicule($vehicule);
        $resa->setStatut($statut_resa_en_attente);

        if ($filtered) {
            $resa->setDateDebut($from);

templates/accueil/access_denied.html.twig
{% extends 'base.html.twig' %}

{% block body %}

	<div class="fr-grid-row">

		<div class="fr-col-12 fr-text--center fr-mt-4w">
			<h1 class="fr-h3">
				Vous n'avez pas accès à cette application
			</h1>

			<p>
				Le périmètre de réservation pour le pool de véhicules est ouvert en fonction de l'unité bénéficiaire, de la manière suivante:
			</p>

			<ul>
				<li>niveau
					<span class="bold">compagnie / SR / EDCF / AGIGN</span>
					&rarr; pour les unités de leur périmètre et les cellules / groupes d'enquête qui leur sont rattachés,</li>
				<li>niveau
					<span class="bold">MPF / GIR / BGTA</span>
					&rarr; pour ces unités,</li>
				<li>niveau
					<span class="bold">SAJ / OAPJR 1 et 2</span>
					&rarr; pour les unités SOLC, SAj, BOE.</li>
			</ul>

			<p class="fr-mt-2w">
				Veuillez prendre attache avec le gestionnaire correspondant à votre unité d'appartenance afin qu'il procède, à votre profit, à la réservation d'un véhicule.
			</p>

		</div>

	</div>


{% endblock %}

templates/accueil/liste.html.twig
{% extends 'base.html.twig' %}

{% block body %}

	{# Fil d'Arianne #}
	<nav role="navigation" class="hide-s fr-breadcrumb" aria-label="vous êtes ici :">
		<button class="fr-breadcrumb__button" aria-expanded="false" aria-controls="breadcrumb-1">Voir le fil d’Ariane</button>
		<div class="fr-collapse" id="breadcrumb-1">
			<ol class="fr-breadcrumb__list">
				<li>
					<a class="fr-breadcrumb__link" aria-current="page">Accueil</a>
				</li>
			</ol>
		</div>
	</nav>

	<div class="fr-grid-row fr-grid-row--gutters">

    <p class="cs-nb-vehicules fr-col-sm-12 fr-h6">{{ vehicules|length }}&nbsp;véhicules disponibles.</p>

		{% for vehicule in vehicules %}

			<div class="cs-card fr-col-sm-12 fr-mb-2w bordered hoverable shadow">
				<figure class="cs-img-container left">
					<img class="cs-img" src="{{ asset('images/4L.jpg') }}" alt="Renault 4l sérigraphiée"/>
					<figcaption class="hidden">Renault 4l sérigraphiée</figcaption>
				</figure>

				<div class="left cs-descr-container">
					<dl>
						<dt class="cs-marque fr-h6">{{vehicule.marque}}&nbsp;<span class="cs-modele">{{vehicule.modele}}</span>
						</dt>
						{% if (vehicule.motorisation ~ vehicule.finition) is empty %}
							<br/>
						{% else %}
							<dd>{{vehicule.motorisation ~ ' ' ~ vehicule.finition}}</dd>
						{% endif %}
						<dd>
							<ul class="fr-tags-group cs-tags">
								<li>
									<p class="fr-tag fr-tag--sm">{{vehicule.transmission.code}}</p>
								</li>
								<li>
									<p class="fr-tag fr-tag--sm">{{vehicule.carburant.libelle}}</p>
								</li>
								<li>
									<p class="fr-tag fr-tag--sm">{{vehicule.categorie.libelle}}</p>
								</li>
							</ul>
						</dd>
						<dd>
							{% for i in range(1, vehicule.NbPlaces) %}
								<i class="cs-user-icon fr-btn fr-icon-user-line fr-btn--icon-left"></i>
							{% endfor %}
						</dd>
					</dl>
				</div>
			</div>
		{% endfor %}

	</div>

{% endblock %}

templates/accueil/login.html.twig
{% extends 'base.html.twig' %}

{% block body %}

  <div class="fr-grid-row">

    {{ form_start(form) }}

    <div class="fr-mt-12w fr-col-8 fr-col-offset-2">

      <div class="fr-select-group{{ result == false ? ' fr-select-group--error' : '' }}">

        <label class="fr-label" for="select-nigend">
          Chargement d'un nigend dans la base pour test :
        </label>

        <input class="fr-input" list="users-list" type="text" id="select-nigend" name="select-nigend">

        <datalist id="users-list">
          {% for user in users %}
            <option value="{{ user.nigend }}">
              {{ user.nigend ~ ' (' ~ user.profil ~ ' - ' ~ user.departement ~ ')' }}
            </option>
          {% endfor %}
        </datalist> 

        <p id="select-error-desc-error" class="fr-error-text{{ result == false ? '' : ' hidden' }}">
          Aucun nigend sélectionné.
        </p>

        {{ form_widget(form.nigend) }}

      </div>

      <br/>

      <input type="submit" class="fr-btn fr-btn--primary" value="Charger le profil" />

    </div>

    {{ form_end(form) }}

  </div>

{% endblock %}

templates/accueil/reserver.html.twig
{% extends 'base.html.twig' %}

{% block body %}

	{{ include('accueil/reserver/modale_debut.html.twig' )}}

	{{ include('accueil/reserver/modale_fin.html.twig' )}}

	{{ include('accueil/reserver/fil_arianne.html.twig' )}}

	{# fiche véhicule #}
	<div
		id="fiche-vehicule" class="cs-fiche-vehicule">

		{# GALLERIE #}
		{% set len = vehicule.photos|length %}

		<div
			class="cs-gallerie fr-grid-row fr-grid-row--gutters">
			{# vue principale #}
			<figure class="fr-col-{{ len <= 1 ? '12' : len == 2 ? '6' : '9' }}">
				<img src="{{ len > 0 ? asset('images/uploads/' ~ vehicule.photos[0].path) : asset('images/no_image.jpg') }}" class="fr-responsive-img cs-figure cs-figure--main" alt="Vue principale du véhicule">
				<figcaption class="hidden">
					Vue principale du véhicule
				</figcaption>
			</figure>

			{# vue de profil #}
			{% if(len > 1) %}
				<div class="fr-col-{{ len == 2 ? '6' : '3 fr-mt-1w' }}">
					<figure class="cs-figure">
						<button class="fr-btn cs-gallerie-btn">
							<img src="{{ asset('images/uploads/' ~ vehicule.photos[1].path) }}" class="fr-responsive-img" alt="Vue de l'avant du véhicule"></button>
						<figcaption class="hidden">
							Vue de profil du véhicule
						</figcaption>
					</figure>

					{# vue de l'avant #}
					{% if(len > 2) %}
						<figure class="cs-figure">
							<button class="fr-btn cs-gallerie-btn">
								<img src="{{ asset('images/uploads/' ~ vehicule.photos[2].path) }}" class="fr-responsive-img" alt="Vue de l'avant du véhicule"></button>
							<figcaption class="hidden">
								Vue de l'avant du véhicule
							</figcaption>
						</figure>
					{% endif %}

					{# vue de l'arrière #}
					{% if(len > 3) %}
						<figure class="cs-figure">
							<button class="fr-btn cs-gallerie-btn">
								<img src="{{ asset('images/uploads/' ~ vehicule.photos[3].path) }}" class="fr-responsive-img" alt="Vue de l'arrière du véhicule"></button>
							<figcaption class="hidden">
								Vue de l'arrière du véhicule
							</figcaption>
						</figure>
					{% endif %}
				</div>
			{% endif %}
		</div>

		{# FIN GALERIE #}

		{# DESCRIPTION VL #}
		<dl class="fr-col-12">
			<dt class="cs-marque">
				{{ vehicule.marque }}
				<span class="cs-modele">
					{{ vehicule.modele }}
				</span>
			</dt>

			{% if (vehicule.motorisation ~ vehicule.finition) is empty %}
				<br/>
			{% else %}
				<dd>
					{{ vehicule.motorisation ~ ' ' ~ vehicule.finition }}
				</dd>
			{% endif %}
			<dd>
				<ul class="fr-tags-group cs-tags">
					<li>
						<p class="fr-tag fr-tag--sm fr-fi-map-pin-2-fill fr-tag--icon-left cs-location-tag" title="{{ vehicule.unite.nomLong }}">
							{{ vehicule.unite.nomCourt }}
						</p>
					</li>
					<li>
						<p class="fr-tag fr-tag--sm">
							{{ vehicule.transmission.code }}
						</p>
					</li>
					<li>
						<p class="fr-tag fr-tag--sm">
							{{ vehicule.carburant.libelle }}
						</p>
					</li>
					<li>
						<p class="fr-tag fr-tag--sm">
							{{ vehicule.NbPlaces }}
							{{ vehicule.NbPlaces > 1 ? 'places' : 'place' }}
						</p>
					</li>
				</ul>
			</dd>
			{% if vehicule.restriction.code != 'NONE' and vehicule.restriction is not empty %}
				{% set badge_class = vehicule.restriction.code != "AVT_JGT" ? 'info' : 'warning' %}
				<dd>
					<div class="fr-alert fr-alert--{{ badge_class }}">
						<h3 class="fr-alert__title">{{ vehicule.restriction.description }}</h3>
					</div>
				</dd>
			{% endif %}
		</dl>
		{# FIN DESCRIPTION VL #}

		{# INFORMATIONS #}
		<div class="fr-col-12">
			<p class="cs-informations">
				Informations
			</p>
			<p class="fr-mt-2w">
				{% if vehicule.observation %}
					{{ vehicule.observation}}
				{% else %}
					Néant
				{% endif %}
			</p>
		</div>
		{# FIN INFORMATIONS #}

		{# JE RÉSERVE #}

		{{ form_start(form) }}

		<div class="fr-col-12">
			<p class="cs-informations">
				Disponibilités
			</p>

			<div id="cs-filtres-container" class="cs-filtres-container">

				<input id="form-field--date_debut" type="hidden" name="{{ field_name(form.date_debut) }}" value="{{ field_value(form.date_debut) }}" class="form-control">

				<input id="form-field--heure_debut" type="hidden" name="{{ field_name(form.heure_debut) }}" value="{{ field_value(form.heure_debut) }}" class="form-control">

				<input id="form-field--date_fin" type="hidden" name="{{ field_name(form.date_fin) }}" value="{{ field_value(form.date_fin) }}" class="form-control">

				<input id="form-field--heure_fin" type="hidden" name="{{ field_name(form.heure_fin) }}" value="{{ field_value(form.heure_fin) }}" class="form-control">

				<input id="form-field--user" type="hidden" name="{{ field_name(form.user) }}" value="{{ field_value(form.user) }}" class="form-control">

				<input id="form-field--vehicule" type="hidden" name="{{ field_name(form.vehicule) }}" value="{{ field_value(form.vehicule) }}" class="form-control">

				<input
				id="form-field--statut" type="hidden" name="{{ field_name(form.statut) }}" value="{{ field_value(form.statut) }}" class="form-control">

				{# DE ... -> À ... #}
				<div class="cs-btn-ctnr cs-date-ctnr">
					<button type="button" id="cs-btn--from" class="bordered cs-btn cs-btn-from-to cs-btn--left">
						<span class="cs-from-to">
							Début
						</span>
						<span id="select-from-date--target" class="cs-from-to-value">
							<div id="from-value--date" class="cs-from-to-value--date">
								{{ filtered ? from.date : '__' }}&nbsp;<span class="hide-s">{{ filtered ? year}}</span>
							</div>
							<div id="from-value--heure" class="cs-from-to-value--heure">
								{{ filtered ? from.heure }}
							</div>
						</span>
					</button>
					<div class="separator"></div>
					<button type="button" id="cs-btn--to" class="cs-btn cs-btn-from-to cs-btn--right">
						<span class=" cs-from-to">
							Fin
						</span>
						<span id="select-to-date--target" class="cs-from-to-value">
							<div id="to-value--date" class="cs-from-to-value--date">
								{{ filtered ? to.date : '__' }}&nbsp;<span class="hide-s">{{ filtered ? year}}</span>
							</div>
							<div id="to-value--heure" class="cs-from-to-value--heure">
								{{ filtered ? to.heure }}
							</div>
						</span>
					</button>
				</div>

				{# Bandeau d'information #}
				<div id="bandeau-info" class="fr-notice fr-notice--warning hidden">
					<div class="fr-container">
						<div class="fr-notice__body">
							<p>
								<span class="fr-notice__title">Conflit</span>
							</p>
							<p class="fr-notice__desc">
								Il y a déjà une réservation dans la période que vous venez de sélectionner.
							</p>
							{# </p> #}
							{# <button title="Masquer le message" onclick="const notice = this.parentNode.parentNode.parentNode; notice.parentNode.removeChild(notice)" id="button-1305" class="fr-btn--close fr-btn">Masquer le message</button> #}
						</div>
					</div>
				</div>

				<div id="form-submit-ctnr" class="{{filtered ? '' : 'hidden ' }}fr-btns-group--right fr-mt-2w fr-mr-1w">
					<div>

						<button id="form-submit-btn" aria-controls="modal-select_valideur" data-fr-opened="false" type="button" class="fr-btn fr-btn--md fr-fi-arrow-right-line fr-btn--icon-right">
							Je réserve
						</button>

					</div>
				</div>

			</div>
		</div>

		{{ include('accueil/reserver/modale_ope.html.twig')}}

		{# {{ include('accueil/reserver/modale_avant_jugement.html.twig')}} #}

		{{ form_end(form) }}

		{# FIN JE RÉSERVE #}

		{{ include('accueil/reserver/calendriers.html.twig')}}

	</div>{# fin fiche véhicule #}{% endblock %}